#ifndef DEFS_H
#define DEFS_H

/* Array Indices */
#define ACCEPT 0
#define ACCEPT_CHARSET 1
#define ACCEPT_ENCODING 2
#define ACCEPT_LANGUAGE 3
#define ALLOW 4
#define AUTHORIZATION 5
#define BASE 6
#define CACHE_CONTROL 7
#define CONNECTION 8
#define CONTENT_ENCODING 9
#define CONTENT_LANGUAGE 10
#define CONTENT_LENGTH 11
#define CONTENT_MD5 12
#define CONTENT_RANGE 13
#define CONTENT_TYPE 14
#define CONTENT_VERSION 15
#define DATE 16
#define DERIVED_FROM 17
#define EXPIRES 18
#define FORWARDED 19
#define FROM 20
#define HOST 21
#define IF_MODIFIED_SINCE 22
#define KEEP_ALIVE 23
#define LAST_MODIFIED 24
#define LINK 25
#define LOCATION 26
#define MIME_VERSION 27
#define PRAGMA 28
#define PROXY_AUTHENTICATE 29
#define PROXY_AUTHORIZATION 30
#define PUBLIC 31
#define RANGE 32
#define REFERER 33
#define REFRESH 34
#define RETRY_AFTER 35
#define SERVER 36
#define TITLE 37
#define TRANSFER_ENCODING 38
#define UNLESS 39
#define UPGRADE 40
#define URI 41
#define USER_AGENT 42
#define WWW_AUTHENTICATE 43

#define HTTP_MAX_FIELDS 44

 /* ACCEPT */
 /* ACCEPT_CHARSET */
 /* ACCEPT_ENCODING */
 /* ACCEPT_LANGUAGE */
 /* ALLOW */
 /* AUTHORIZATION */
 /* BASE */
 /* CACHE_CONTROL */
 /* CONNECTION */
 /* CONTENT_ENCODING */
 /* CONTENT_LANGUAGE */
 /* CONTENT_LENGTH */
 /* CONTENT_MD5 */
 /* CONTENT_RANGE */
 /* CONTENT_TYPE */
 /* CONTENT_VERSION */
 /* DATE */
 /* DERIVED_FROM */
 /* EXPIRES */
 /* FORWARDED */
 /* FROM */
 /* HOST */
 /* IF_MODIFIED_SINCE */
 /* KEEP_ALIVE */
 /* LAST_MODIFIED */
 /* LINK */
 /* LOCATION */
 /* MIME_VERSION */
 /* PRAGMA */
 /* PROXY_AUTHENTICATE */
 /* PROXY_AUTHORIZATION */
 /* PUBLIC */
 /* RANGE */
 /* REFERER */
 /* REFRESH */
 /* RETRY_AFTER */
 /* SERVER */
 /* TITLE */
 /* TRANSFER_ENCODING */
 /* UNLESS */
 /* UPGRADE */
 /* URI */
 /* USER_AGENT */
 /* WWW_AUTHENTICATE */

#endif /* defs.h */

